---
metrics:
  - name: snmp_ifHCInOctets
    description: Inbound traffic on the interface
    type: counter
    labels: [host, ip, interface]
    sequence:
      # Group: apple
      - time: 5
        values: 0-20
        operation: inc
        labels:
          host: apple
          ip: 10.10.11.2
          interface: eth0
      - eval_time: 5
        operation: set
        labels:
          host: apple
          ip: 10.10.11.2
          interface: eth0
      # Group: grape
      - time: 5
        eval_time: 1
        values: 0-20
        operation: inc
        labels:
          host: grape
          ip: 10.10.11.5
          interface: eth0
      - time: 5
        eval_time: 1
        values: 0-5
        operation: dec
        labels:
          host: grape
          ip: 10.10.11.5
          interface: eth0
      # Group: zala
      - time: 5
        eval_time: 1
        value: 3
        operation: inc
        labels:
          host: zala
          ip: 10.10.11.8
          interface: eth0
