---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PDG_CONFIG
          value: /pdg/config.yml
        ports:
        - name: metrics
          containerPort: 9000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: metrics
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: metrics
            scheme: HTTP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /pdg/
      - name: config-reloader
        image: quay.io/coreos/configmap-reload:v0.0.1
        args:
        - -webhook-url=http://localhost:9000/-/reload
        - -volume-dir=/pdg/
        - -webhook-method=GET
        resources:
          limits:
            cpu: 5m
            memory: 10Mi
          requests:
            cpu: 5m
            memory: 10Mi
        volumeMounts:
        - name: config
          mountPath: /pdg/
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ include "app.fullname" . }}
