---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    prometheus: kube-prometheus
    # this label is needed in case of using default kube-prometheus-stack helm chart
    # so that prometheus picks this up
    app.kubernetes.io/managed-by: Helm
spec:
  endpoints:
  - interval: 10s
    path: /metrics/
    port: metrics
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
